pipeline
{
agent {
  label 'agent1'
}

tools {
  maven 'maven'
}

stages{
    stage ('Build')
    {
        steps {
            sh 'mvn clean package'
            }
        post {
            success {
                archieveArtifacts artifacts: '**/target/*.war'
                }       
             }
    }
    // stage ('Test') 
    // {
    //     steps {
    //         echo "This is a test stage"
    //     }
    // }
    // stage ('Deploy') 
    // {
    //     steps {
    //         echo "This is a deploy stage"
    //     }
    // }
 }
}